### ISSUE TITLE
安裝並設定API ID和API KEY之後不顯示登錄按鈕

### ISSUE THREAD

**Issue by kinosang** [fantasticfears/qq_connect#3]
Discourse版本：1.2.0.beta5

**Comment by fantasticfears** [comment]
你是怎么安装的呢？是按照 docker 安装法要求的方法安装的么？

安装完成后不填写 key 和 secret 就应该出现对应的登录方法了。

**Comment by kinosang** [comment]
@fantasticfears 之前用docker方法安裝沒有顯示，現在是非官方ubuntu安裝，`git clone` 之後 `rake assets:precompile` 也沒有作用。

**Comment by fantasticfears** [comment]
能详细地描述一下你是怎么配置配置文件的嘛？我开发环境中没问题的样子，但是生产环境似乎有问题

**Comment by kinosang** [comment]
@fantasticfears 
Docker安裝方式：
```
hooks:
  after_code:
    - exec:
        cd: $home/plugins
        cmd:
          - mkdir -p plugins
          - git clone https://github.com/discourse/docker_manager.git
          - git clone https://github.com/crob611/discourse-image-gallery.git
          - git clone https://github.com/tcreativo/plugin_discourse_dynamic_sidebar.git
          - git clone https://github.com/fantasticfears/qq_connect.git
          - git clone https://github.com/fantasticfears/weibo-login.git
```
然後 `./launcher bootstrap app` （安裝discourse之前直接添加plugins）

同樣沒有生效的包括 `plugin_discourse_dynamic_sidebar` 和微博
